apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-my-app-container
          image: 910436101907.dkr.ecr.us-east-1.amazonaws.com/capstone:86139ae68304482e44f5e7bb44fa62c66f580c96
            - containerPort: 80