apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1    
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-my-app-container
          image: 910436101907.dkr.ecr.us-east-1.amazonaws.com/capstone:611d5026fa8ff196002770380a25075409c4f349
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer