version: 2.1

jobs:
  lint-code:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command: |
            apt-get update
            apt-get install -y curl
            apt-get install -y build-essential
            apt-get install -y liblapack-dev
            apt-get install -y gfortran
            apt-get install -y libblas-dev
            apt-get install -y libopenblas-dev

            make setup
            make install_hadolint
            make install
      - run:
          name: Run Lint Checks
          command: make lint             

  build-image:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t todo-app:$TAG .
            echo Docker build is successful. Push is missing
            
workflows:
  default:
    jobs: 
      - lint-code
      - build-image:
          requires: [lint-code]