version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.0.0
  aws-ecr: circleci/aws-ecr@8.1.3
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  lint-code:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command: |
            apt-get update
            apt-get install -y curl
            apt-get install -y build-essential
            apt-get install -y liblapack-dev
            apt-get install -y gfortran
            apt-get install -y libblas-dev
            apt-get install -y libopenblas-dev

            make setup
            make install_hadolint
            make install
      - run:
          name: Run Lint Checks
          command: make lint             

  create-update:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install envsubst
          command: |
            sudo apt-get install -y gettext-base
      - run: 
          name: update deployment file
          command: |
            envsubst < deployment.yml > updated-deployment.yml    
      - kubernetes/install-kubectl
      - aws-eks/update-kubeconfig-with-authenticator:
          authenticator-release-tag: "v0.5.6"
          cluster-name: capstone
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: ./deployment.yaml
          resource-name: todo-app-deployment
          show-kubectl-command: true         

workflows:
  default:
    jobs: 
      # - lint-code
      # - aws-ecr/build-and-push-image:
      #     context: aws-dev
      #     create-repo: false
      #     dockerfile: Dockerfile
      #     path: .
      #     repo: capstone
      #     tag: "$CIRCLE_SHA1"
      #     requires: [lint-code]
      - create-update #:
          # requires: [aws-ecr/build-and-push-image]